apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service
  labels:
    app.kubernetes.io/instance: react-app
spec:
  selector:
    app: react-frontend
  type: NodePort
  ports:
    - port: 80
      targetPort: 80       # ✅ changed from 3000 to 80
      nodePort: 30007
      protocol: TCP
